# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.20.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.20.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kalunik/CLionProjects/push_swap

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kalunik/CLionProjects/push_swap

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.20.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.20.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kalunik/CLionProjects/push_swap/CMakeFiles /Users/kalunik/CLionProjects/push_swap//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kalunik/CLionProjects/push_swap/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named push_swap

# Build rule for target.
push_swap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 push_swap
.PHONY : push_swap

# fast build rule for target.
push_swap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/build
.PHONY : push_swap/fast

libft/ft_atoi.o: libft/ft_atoi.c.o
.PHONY : libft/ft_atoi.o

# target to build an object file
libft/ft_atoi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_atoi.c.o
.PHONY : libft/ft_atoi.c.o

libft/ft_atoi.i: libft/ft_atoi.c.i
.PHONY : libft/ft_atoi.i

# target to preprocess a source file
libft/ft_atoi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_atoi.c.i
.PHONY : libft/ft_atoi.c.i

libft/ft_atoi.s: libft/ft_atoi.c.s
.PHONY : libft/ft_atoi.s

# target to generate assembly for a file
libft/ft_atoi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_atoi.c.s
.PHONY : libft/ft_atoi.c.s

libft/ft_bzero.o: libft/ft_bzero.c.o
.PHONY : libft/ft_bzero.o

# target to build an object file
libft/ft_bzero.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_bzero.c.o
.PHONY : libft/ft_bzero.c.o

libft/ft_bzero.i: libft/ft_bzero.c.i
.PHONY : libft/ft_bzero.i

# target to preprocess a source file
libft/ft_bzero.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_bzero.c.i
.PHONY : libft/ft_bzero.c.i

libft/ft_bzero.s: libft/ft_bzero.c.s
.PHONY : libft/ft_bzero.s

# target to generate assembly for a file
libft/ft_bzero.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_bzero.c.s
.PHONY : libft/ft_bzero.c.s

libft/ft_calloc.o: libft/ft_calloc.c.o
.PHONY : libft/ft_calloc.o

# target to build an object file
libft/ft_calloc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_calloc.c.o
.PHONY : libft/ft_calloc.c.o

libft/ft_calloc.i: libft/ft_calloc.c.i
.PHONY : libft/ft_calloc.i

# target to preprocess a source file
libft/ft_calloc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_calloc.c.i
.PHONY : libft/ft_calloc.c.i

libft/ft_calloc.s: libft/ft_calloc.c.s
.PHONY : libft/ft_calloc.s

# target to generate assembly for a file
libft/ft_calloc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_calloc.c.s
.PHONY : libft/ft_calloc.c.s

libft/ft_isalnum.o: libft/ft_isalnum.c.o
.PHONY : libft/ft_isalnum.o

# target to build an object file
libft/ft_isalnum.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_isalnum.c.o
.PHONY : libft/ft_isalnum.c.o

libft/ft_isalnum.i: libft/ft_isalnum.c.i
.PHONY : libft/ft_isalnum.i

# target to preprocess a source file
libft/ft_isalnum.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_isalnum.c.i
.PHONY : libft/ft_isalnum.c.i

libft/ft_isalnum.s: libft/ft_isalnum.c.s
.PHONY : libft/ft_isalnum.s

# target to generate assembly for a file
libft/ft_isalnum.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_isalnum.c.s
.PHONY : libft/ft_isalnum.c.s

libft/ft_isalpha.o: libft/ft_isalpha.c.o
.PHONY : libft/ft_isalpha.o

# target to build an object file
libft/ft_isalpha.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_isalpha.c.o
.PHONY : libft/ft_isalpha.c.o

libft/ft_isalpha.i: libft/ft_isalpha.c.i
.PHONY : libft/ft_isalpha.i

# target to preprocess a source file
libft/ft_isalpha.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_isalpha.c.i
.PHONY : libft/ft_isalpha.c.i

libft/ft_isalpha.s: libft/ft_isalpha.c.s
.PHONY : libft/ft_isalpha.s

# target to generate assembly for a file
libft/ft_isalpha.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_isalpha.c.s
.PHONY : libft/ft_isalpha.c.s

libft/ft_isascii.o: libft/ft_isascii.c.o
.PHONY : libft/ft_isascii.o

# target to build an object file
libft/ft_isascii.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_isascii.c.o
.PHONY : libft/ft_isascii.c.o

libft/ft_isascii.i: libft/ft_isascii.c.i
.PHONY : libft/ft_isascii.i

# target to preprocess a source file
libft/ft_isascii.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_isascii.c.i
.PHONY : libft/ft_isascii.c.i

libft/ft_isascii.s: libft/ft_isascii.c.s
.PHONY : libft/ft_isascii.s

# target to generate assembly for a file
libft/ft_isascii.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_isascii.c.s
.PHONY : libft/ft_isascii.c.s

libft/ft_isdigit.o: libft/ft_isdigit.c.o
.PHONY : libft/ft_isdigit.o

# target to build an object file
libft/ft_isdigit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_isdigit.c.o
.PHONY : libft/ft_isdigit.c.o

libft/ft_isdigit.i: libft/ft_isdigit.c.i
.PHONY : libft/ft_isdigit.i

# target to preprocess a source file
libft/ft_isdigit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_isdigit.c.i
.PHONY : libft/ft_isdigit.c.i

libft/ft_isdigit.s: libft/ft_isdigit.c.s
.PHONY : libft/ft_isdigit.s

# target to generate assembly for a file
libft/ft_isdigit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_isdigit.c.s
.PHONY : libft/ft_isdigit.c.s

libft/ft_isprint.o: libft/ft_isprint.c.o
.PHONY : libft/ft_isprint.o

# target to build an object file
libft/ft_isprint.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_isprint.c.o
.PHONY : libft/ft_isprint.c.o

libft/ft_isprint.i: libft/ft_isprint.c.i
.PHONY : libft/ft_isprint.i

# target to preprocess a source file
libft/ft_isprint.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_isprint.c.i
.PHONY : libft/ft_isprint.c.i

libft/ft_isprint.s: libft/ft_isprint.c.s
.PHONY : libft/ft_isprint.s

# target to generate assembly for a file
libft/ft_isprint.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_isprint.c.s
.PHONY : libft/ft_isprint.c.s

libft/ft_itoa.o: libft/ft_itoa.c.o
.PHONY : libft/ft_itoa.o

# target to build an object file
libft/ft_itoa.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_itoa.c.o
.PHONY : libft/ft_itoa.c.o

libft/ft_itoa.i: libft/ft_itoa.c.i
.PHONY : libft/ft_itoa.i

# target to preprocess a source file
libft/ft_itoa.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_itoa.c.i
.PHONY : libft/ft_itoa.c.i

libft/ft_itoa.s: libft/ft_itoa.c.s
.PHONY : libft/ft_itoa.s

# target to generate assembly for a file
libft/ft_itoa.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_itoa.c.s
.PHONY : libft/ft_itoa.c.s

libft/ft_memccpy.o: libft/ft_memccpy.c.o
.PHONY : libft/ft_memccpy.o

# target to build an object file
libft/ft_memccpy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memccpy.c.o
.PHONY : libft/ft_memccpy.c.o

libft/ft_memccpy.i: libft/ft_memccpy.c.i
.PHONY : libft/ft_memccpy.i

# target to preprocess a source file
libft/ft_memccpy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memccpy.c.i
.PHONY : libft/ft_memccpy.c.i

libft/ft_memccpy.s: libft/ft_memccpy.c.s
.PHONY : libft/ft_memccpy.s

# target to generate assembly for a file
libft/ft_memccpy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memccpy.c.s
.PHONY : libft/ft_memccpy.c.s

libft/ft_memchr.o: libft/ft_memchr.c.o
.PHONY : libft/ft_memchr.o

# target to build an object file
libft/ft_memchr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memchr.c.o
.PHONY : libft/ft_memchr.c.o

libft/ft_memchr.i: libft/ft_memchr.c.i
.PHONY : libft/ft_memchr.i

# target to preprocess a source file
libft/ft_memchr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memchr.c.i
.PHONY : libft/ft_memchr.c.i

libft/ft_memchr.s: libft/ft_memchr.c.s
.PHONY : libft/ft_memchr.s

# target to generate assembly for a file
libft/ft_memchr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memchr.c.s
.PHONY : libft/ft_memchr.c.s

libft/ft_memcmp.o: libft/ft_memcmp.c.o
.PHONY : libft/ft_memcmp.o

# target to build an object file
libft/ft_memcmp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memcmp.c.o
.PHONY : libft/ft_memcmp.c.o

libft/ft_memcmp.i: libft/ft_memcmp.c.i
.PHONY : libft/ft_memcmp.i

# target to preprocess a source file
libft/ft_memcmp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memcmp.c.i
.PHONY : libft/ft_memcmp.c.i

libft/ft_memcmp.s: libft/ft_memcmp.c.s
.PHONY : libft/ft_memcmp.s

# target to generate assembly for a file
libft/ft_memcmp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memcmp.c.s
.PHONY : libft/ft_memcmp.c.s

libft/ft_memcpy.o: libft/ft_memcpy.c.o
.PHONY : libft/ft_memcpy.o

# target to build an object file
libft/ft_memcpy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memcpy.c.o
.PHONY : libft/ft_memcpy.c.o

libft/ft_memcpy.i: libft/ft_memcpy.c.i
.PHONY : libft/ft_memcpy.i

# target to preprocess a source file
libft/ft_memcpy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memcpy.c.i
.PHONY : libft/ft_memcpy.c.i

libft/ft_memcpy.s: libft/ft_memcpy.c.s
.PHONY : libft/ft_memcpy.s

# target to generate assembly for a file
libft/ft_memcpy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memcpy.c.s
.PHONY : libft/ft_memcpy.c.s

libft/ft_memmove.o: libft/ft_memmove.c.o
.PHONY : libft/ft_memmove.o

# target to build an object file
libft/ft_memmove.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memmove.c.o
.PHONY : libft/ft_memmove.c.o

libft/ft_memmove.i: libft/ft_memmove.c.i
.PHONY : libft/ft_memmove.i

# target to preprocess a source file
libft/ft_memmove.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memmove.c.i
.PHONY : libft/ft_memmove.c.i

libft/ft_memmove.s: libft/ft_memmove.c.s
.PHONY : libft/ft_memmove.s

# target to generate assembly for a file
libft/ft_memmove.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memmove.c.s
.PHONY : libft/ft_memmove.c.s

libft/ft_memset.o: libft/ft_memset.c.o
.PHONY : libft/ft_memset.o

# target to build an object file
libft/ft_memset.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memset.c.o
.PHONY : libft/ft_memset.c.o

libft/ft_memset.i: libft/ft_memset.c.i
.PHONY : libft/ft_memset.i

# target to preprocess a source file
libft/ft_memset.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memset.c.i
.PHONY : libft/ft_memset.c.i

libft/ft_memset.s: libft/ft_memset.c.s
.PHONY : libft/ft_memset.s

# target to generate assembly for a file
libft/ft_memset.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_memset.c.s
.PHONY : libft/ft_memset.c.s

libft/ft_putchar_fd.o: libft/ft_putchar_fd.c.o
.PHONY : libft/ft_putchar_fd.o

# target to build an object file
libft/ft_putchar_fd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_putchar_fd.c.o
.PHONY : libft/ft_putchar_fd.c.o

libft/ft_putchar_fd.i: libft/ft_putchar_fd.c.i
.PHONY : libft/ft_putchar_fd.i

# target to preprocess a source file
libft/ft_putchar_fd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_putchar_fd.c.i
.PHONY : libft/ft_putchar_fd.c.i

libft/ft_putchar_fd.s: libft/ft_putchar_fd.c.s
.PHONY : libft/ft_putchar_fd.s

# target to generate assembly for a file
libft/ft_putchar_fd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_putchar_fd.c.s
.PHONY : libft/ft_putchar_fd.c.s

libft/ft_putendl_fd.o: libft/ft_putendl_fd.c.o
.PHONY : libft/ft_putendl_fd.o

# target to build an object file
libft/ft_putendl_fd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_putendl_fd.c.o
.PHONY : libft/ft_putendl_fd.c.o

libft/ft_putendl_fd.i: libft/ft_putendl_fd.c.i
.PHONY : libft/ft_putendl_fd.i

# target to preprocess a source file
libft/ft_putendl_fd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_putendl_fd.c.i
.PHONY : libft/ft_putendl_fd.c.i

libft/ft_putendl_fd.s: libft/ft_putendl_fd.c.s
.PHONY : libft/ft_putendl_fd.s

# target to generate assembly for a file
libft/ft_putendl_fd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_putendl_fd.c.s
.PHONY : libft/ft_putendl_fd.c.s

libft/ft_putnbr_fd.o: libft/ft_putnbr_fd.c.o
.PHONY : libft/ft_putnbr_fd.o

# target to build an object file
libft/ft_putnbr_fd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_putnbr_fd.c.o
.PHONY : libft/ft_putnbr_fd.c.o

libft/ft_putnbr_fd.i: libft/ft_putnbr_fd.c.i
.PHONY : libft/ft_putnbr_fd.i

# target to preprocess a source file
libft/ft_putnbr_fd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_putnbr_fd.c.i
.PHONY : libft/ft_putnbr_fd.c.i

libft/ft_putnbr_fd.s: libft/ft_putnbr_fd.c.s
.PHONY : libft/ft_putnbr_fd.s

# target to generate assembly for a file
libft/ft_putnbr_fd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_putnbr_fd.c.s
.PHONY : libft/ft_putnbr_fd.c.s

libft/ft_putstr_fd.o: libft/ft_putstr_fd.c.o
.PHONY : libft/ft_putstr_fd.o

# target to build an object file
libft/ft_putstr_fd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_putstr_fd.c.o
.PHONY : libft/ft_putstr_fd.c.o

libft/ft_putstr_fd.i: libft/ft_putstr_fd.c.i
.PHONY : libft/ft_putstr_fd.i

# target to preprocess a source file
libft/ft_putstr_fd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_putstr_fd.c.i
.PHONY : libft/ft_putstr_fd.c.i

libft/ft_putstr_fd.s: libft/ft_putstr_fd.c.s
.PHONY : libft/ft_putstr_fd.s

# target to generate assembly for a file
libft/ft_putstr_fd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_putstr_fd.c.s
.PHONY : libft/ft_putstr_fd.c.s

libft/ft_split.o: libft/ft_split.c.o
.PHONY : libft/ft_split.o

# target to build an object file
libft/ft_split.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_split.c.o
.PHONY : libft/ft_split.c.o

libft/ft_split.i: libft/ft_split.c.i
.PHONY : libft/ft_split.i

# target to preprocess a source file
libft/ft_split.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_split.c.i
.PHONY : libft/ft_split.c.i

libft/ft_split.s: libft/ft_split.c.s
.PHONY : libft/ft_split.s

# target to generate assembly for a file
libft/ft_split.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_split.c.s
.PHONY : libft/ft_split.c.s

libft/ft_strchr.o: libft/ft_strchr.c.o
.PHONY : libft/ft_strchr.o

# target to build an object file
libft/ft_strchr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strchr.c.o
.PHONY : libft/ft_strchr.c.o

libft/ft_strchr.i: libft/ft_strchr.c.i
.PHONY : libft/ft_strchr.i

# target to preprocess a source file
libft/ft_strchr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strchr.c.i
.PHONY : libft/ft_strchr.c.i

libft/ft_strchr.s: libft/ft_strchr.c.s
.PHONY : libft/ft_strchr.s

# target to generate assembly for a file
libft/ft_strchr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strchr.c.s
.PHONY : libft/ft_strchr.c.s

libft/ft_strdup.o: libft/ft_strdup.c.o
.PHONY : libft/ft_strdup.o

# target to build an object file
libft/ft_strdup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strdup.c.o
.PHONY : libft/ft_strdup.c.o

libft/ft_strdup.i: libft/ft_strdup.c.i
.PHONY : libft/ft_strdup.i

# target to preprocess a source file
libft/ft_strdup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strdup.c.i
.PHONY : libft/ft_strdup.c.i

libft/ft_strdup.s: libft/ft_strdup.c.s
.PHONY : libft/ft_strdup.s

# target to generate assembly for a file
libft/ft_strdup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strdup.c.s
.PHONY : libft/ft_strdup.c.s

libft/ft_strjoin.o: libft/ft_strjoin.c.o
.PHONY : libft/ft_strjoin.o

# target to build an object file
libft/ft_strjoin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strjoin.c.o
.PHONY : libft/ft_strjoin.c.o

libft/ft_strjoin.i: libft/ft_strjoin.c.i
.PHONY : libft/ft_strjoin.i

# target to preprocess a source file
libft/ft_strjoin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strjoin.c.i
.PHONY : libft/ft_strjoin.c.i

libft/ft_strjoin.s: libft/ft_strjoin.c.s
.PHONY : libft/ft_strjoin.s

# target to generate assembly for a file
libft/ft_strjoin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strjoin.c.s
.PHONY : libft/ft_strjoin.c.s

libft/ft_strlcat.o: libft/ft_strlcat.c.o
.PHONY : libft/ft_strlcat.o

# target to build an object file
libft/ft_strlcat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strlcat.c.o
.PHONY : libft/ft_strlcat.c.o

libft/ft_strlcat.i: libft/ft_strlcat.c.i
.PHONY : libft/ft_strlcat.i

# target to preprocess a source file
libft/ft_strlcat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strlcat.c.i
.PHONY : libft/ft_strlcat.c.i

libft/ft_strlcat.s: libft/ft_strlcat.c.s
.PHONY : libft/ft_strlcat.s

# target to generate assembly for a file
libft/ft_strlcat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strlcat.c.s
.PHONY : libft/ft_strlcat.c.s

libft/ft_strlcpy.o: libft/ft_strlcpy.c.o
.PHONY : libft/ft_strlcpy.o

# target to build an object file
libft/ft_strlcpy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strlcpy.c.o
.PHONY : libft/ft_strlcpy.c.o

libft/ft_strlcpy.i: libft/ft_strlcpy.c.i
.PHONY : libft/ft_strlcpy.i

# target to preprocess a source file
libft/ft_strlcpy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strlcpy.c.i
.PHONY : libft/ft_strlcpy.c.i

libft/ft_strlcpy.s: libft/ft_strlcpy.c.s
.PHONY : libft/ft_strlcpy.s

# target to generate assembly for a file
libft/ft_strlcpy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strlcpy.c.s
.PHONY : libft/ft_strlcpy.c.s

libft/ft_strlen.o: libft/ft_strlen.c.o
.PHONY : libft/ft_strlen.o

# target to build an object file
libft/ft_strlen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strlen.c.o
.PHONY : libft/ft_strlen.c.o

libft/ft_strlen.i: libft/ft_strlen.c.i
.PHONY : libft/ft_strlen.i

# target to preprocess a source file
libft/ft_strlen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strlen.c.i
.PHONY : libft/ft_strlen.c.i

libft/ft_strlen.s: libft/ft_strlen.c.s
.PHONY : libft/ft_strlen.s

# target to generate assembly for a file
libft/ft_strlen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strlen.c.s
.PHONY : libft/ft_strlen.c.s

libft/ft_strmapi.o: libft/ft_strmapi.c.o
.PHONY : libft/ft_strmapi.o

# target to build an object file
libft/ft_strmapi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strmapi.c.o
.PHONY : libft/ft_strmapi.c.o

libft/ft_strmapi.i: libft/ft_strmapi.c.i
.PHONY : libft/ft_strmapi.i

# target to preprocess a source file
libft/ft_strmapi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strmapi.c.i
.PHONY : libft/ft_strmapi.c.i

libft/ft_strmapi.s: libft/ft_strmapi.c.s
.PHONY : libft/ft_strmapi.s

# target to generate assembly for a file
libft/ft_strmapi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strmapi.c.s
.PHONY : libft/ft_strmapi.c.s

libft/ft_strncmp.o: libft/ft_strncmp.c.o
.PHONY : libft/ft_strncmp.o

# target to build an object file
libft/ft_strncmp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strncmp.c.o
.PHONY : libft/ft_strncmp.c.o

libft/ft_strncmp.i: libft/ft_strncmp.c.i
.PHONY : libft/ft_strncmp.i

# target to preprocess a source file
libft/ft_strncmp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strncmp.c.i
.PHONY : libft/ft_strncmp.c.i

libft/ft_strncmp.s: libft/ft_strncmp.c.s
.PHONY : libft/ft_strncmp.s

# target to generate assembly for a file
libft/ft_strncmp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strncmp.c.s
.PHONY : libft/ft_strncmp.c.s

libft/ft_strnstr.o: libft/ft_strnstr.c.o
.PHONY : libft/ft_strnstr.o

# target to build an object file
libft/ft_strnstr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strnstr.c.o
.PHONY : libft/ft_strnstr.c.o

libft/ft_strnstr.i: libft/ft_strnstr.c.i
.PHONY : libft/ft_strnstr.i

# target to preprocess a source file
libft/ft_strnstr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strnstr.c.i
.PHONY : libft/ft_strnstr.c.i

libft/ft_strnstr.s: libft/ft_strnstr.c.s
.PHONY : libft/ft_strnstr.s

# target to generate assembly for a file
libft/ft_strnstr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strnstr.c.s
.PHONY : libft/ft_strnstr.c.s

libft/ft_strrchr.o: libft/ft_strrchr.c.o
.PHONY : libft/ft_strrchr.o

# target to build an object file
libft/ft_strrchr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strrchr.c.o
.PHONY : libft/ft_strrchr.c.o

libft/ft_strrchr.i: libft/ft_strrchr.c.i
.PHONY : libft/ft_strrchr.i

# target to preprocess a source file
libft/ft_strrchr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strrchr.c.i
.PHONY : libft/ft_strrchr.c.i

libft/ft_strrchr.s: libft/ft_strrchr.c.s
.PHONY : libft/ft_strrchr.s

# target to generate assembly for a file
libft/ft_strrchr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strrchr.c.s
.PHONY : libft/ft_strrchr.c.s

libft/ft_strtrim.o: libft/ft_strtrim.c.o
.PHONY : libft/ft_strtrim.o

# target to build an object file
libft/ft_strtrim.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strtrim.c.o
.PHONY : libft/ft_strtrim.c.o

libft/ft_strtrim.i: libft/ft_strtrim.c.i
.PHONY : libft/ft_strtrim.i

# target to preprocess a source file
libft/ft_strtrim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strtrim.c.i
.PHONY : libft/ft_strtrim.c.i

libft/ft_strtrim.s: libft/ft_strtrim.c.s
.PHONY : libft/ft_strtrim.s

# target to generate assembly for a file
libft/ft_strtrim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_strtrim.c.s
.PHONY : libft/ft_strtrim.c.s

libft/ft_substr.o: libft/ft_substr.c.o
.PHONY : libft/ft_substr.o

# target to build an object file
libft/ft_substr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_substr.c.o
.PHONY : libft/ft_substr.c.o

libft/ft_substr.i: libft/ft_substr.c.i
.PHONY : libft/ft_substr.i

# target to preprocess a source file
libft/ft_substr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_substr.c.i
.PHONY : libft/ft_substr.c.i

libft/ft_substr.s: libft/ft_substr.c.s
.PHONY : libft/ft_substr.s

# target to generate assembly for a file
libft/ft_substr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_substr.c.s
.PHONY : libft/ft_substr.c.s

libft/ft_tolower.o: libft/ft_tolower.c.o
.PHONY : libft/ft_tolower.o

# target to build an object file
libft/ft_tolower.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_tolower.c.o
.PHONY : libft/ft_tolower.c.o

libft/ft_tolower.i: libft/ft_tolower.c.i
.PHONY : libft/ft_tolower.i

# target to preprocess a source file
libft/ft_tolower.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_tolower.c.i
.PHONY : libft/ft_tolower.c.i

libft/ft_tolower.s: libft/ft_tolower.c.s
.PHONY : libft/ft_tolower.s

# target to generate assembly for a file
libft/ft_tolower.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_tolower.c.s
.PHONY : libft/ft_tolower.c.s

libft/ft_toupper.o: libft/ft_toupper.c.o
.PHONY : libft/ft_toupper.o

# target to build an object file
libft/ft_toupper.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_toupper.c.o
.PHONY : libft/ft_toupper.c.o

libft/ft_toupper.i: libft/ft_toupper.c.i
.PHONY : libft/ft_toupper.i

# target to preprocess a source file
libft/ft_toupper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_toupper.c.i
.PHONY : libft/ft_toupper.c.i

libft/ft_toupper.s: libft/ft_toupper.c.s
.PHONY : libft/ft_toupper.s

# target to generate assembly for a file
libft/ft_toupper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/libft/ft_toupper.c.s
.PHONY : libft/ft_toupper.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/main.c.s
.PHONY : main.c.s

sources/errors.o: sources/errors.c.o
.PHONY : sources/errors.o

# target to build an object file
sources/errors.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/errors.c.o
.PHONY : sources/errors.c.o

sources/errors.i: sources/errors.c.i
.PHONY : sources/errors.i

# target to preprocess a source file
sources/errors.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/errors.c.i
.PHONY : sources/errors.c.i

sources/errors.s: sources/errors.c.s
.PHONY : sources/errors.s

# target to generate assembly for a file
sources/errors.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/errors.c.s
.PHONY : sources/errors.c.s

sources/fill_array.o: sources/fill_array.c.o
.PHONY : sources/fill_array.o

# target to build an object file
sources/fill_array.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/fill_array.c.o
.PHONY : sources/fill_array.c.o

sources/fill_array.i: sources/fill_array.c.i
.PHONY : sources/fill_array.i

# target to preprocess a source file
sources/fill_array.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/fill_array.c.i
.PHONY : sources/fill_array.c.i

sources/fill_array.s: sources/fill_array.c.s
.PHONY : sources/fill_array.s

# target to generate assembly for a file
sources/fill_array.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/fill_array.c.s
.PHONY : sources/fill_array.c.s

sources/list_operations/add_element.o: sources/list_operations/add_element.c.o
.PHONY : sources/list_operations/add_element.o

# target to build an object file
sources/list_operations/add_element.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/add_element.c.o
.PHONY : sources/list_operations/add_element.c.o

sources/list_operations/add_element.i: sources/list_operations/add_element.c.i
.PHONY : sources/list_operations/add_element.i

# target to preprocess a source file
sources/list_operations/add_element.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/add_element.c.i
.PHONY : sources/list_operations/add_element.c.i

sources/list_operations/add_element.s: sources/list_operations/add_element.c.s
.PHONY : sources/list_operations/add_element.s

# target to generate assembly for a file
sources/list_operations/add_element.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/add_element.c.s
.PHONY : sources/list_operations/add_element.c.s

sources/list_operations/create_list.o: sources/list_operations/create_list.c.o
.PHONY : sources/list_operations/create_list.o

# target to build an object file
sources/list_operations/create_list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/create_list.c.o
.PHONY : sources/list_operations/create_list.c.o

sources/list_operations/create_list.i: sources/list_operations/create_list.c.i
.PHONY : sources/list_operations/create_list.i

# target to preprocess a source file
sources/list_operations/create_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/create_list.c.i
.PHONY : sources/list_operations/create_list.c.i

sources/list_operations/create_list.s: sources/list_operations/create_list.c.s
.PHONY : sources/list_operations/create_list.s

# target to generate assembly for a file
sources/list_operations/create_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/create_list.c.s
.PHONY : sources/list_operations/create_list.c.s

sources/list_operations/element_position_in_list.o: sources/list_operations/element_position_in_list.c.o
.PHONY : sources/list_operations/element_position_in_list.o

# target to build an object file
sources/list_operations/element_position_in_list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/element_position_in_list.c.o
.PHONY : sources/list_operations/element_position_in_list.c.o

sources/list_operations/element_position_in_list.i: sources/list_operations/element_position_in_list.c.i
.PHONY : sources/list_operations/element_position_in_list.i

# target to preprocess a source file
sources/list_operations/element_position_in_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/element_position_in_list.c.i
.PHONY : sources/list_operations/element_position_in_list.c.i

sources/list_operations/element_position_in_list.s: sources/list_operations/element_position_in_list.c.s
.PHONY : sources/list_operations/element_position_in_list.s

# target to generate assembly for a file
sources/list_operations/element_position_in_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/element_position_in_list.c.s
.PHONY : sources/list_operations/element_position_in_list.c.s

sources/list_operations/element_to_top.o: sources/list_operations/element_to_top.c.o
.PHONY : sources/list_operations/element_to_top.o

# target to build an object file
sources/list_operations/element_to_top.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/element_to_top.c.o
.PHONY : sources/list_operations/element_to_top.c.o

sources/list_operations/element_to_top.i: sources/list_operations/element_to_top.c.i
.PHONY : sources/list_operations/element_to_top.i

# target to preprocess a source file
sources/list_operations/element_to_top.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/element_to_top.c.i
.PHONY : sources/list_operations/element_to_top.c.i

sources/list_operations/element_to_top.s: sources/list_operations/element_to_top.c.s
.PHONY : sources/list_operations/element_to_top.s

# target to generate assembly for a file
sources/list_operations/element_to_top.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/element_to_top.c.s
.PHONY : sources/list_operations/element_to_top.c.s

sources/list_operations/ft_listlen.o: sources/list_operations/ft_listlen.c.o
.PHONY : sources/list_operations/ft_listlen.o

# target to build an object file
sources/list_operations/ft_listlen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/ft_listlen.c.o
.PHONY : sources/list_operations/ft_listlen.c.o

sources/list_operations/ft_listlen.i: sources/list_operations/ft_listlen.c.i
.PHONY : sources/list_operations/ft_listlen.i

# target to preprocess a source file
sources/list_operations/ft_listlen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/ft_listlen.c.i
.PHONY : sources/list_operations/ft_listlen.c.i

sources/list_operations/ft_listlen.s: sources/list_operations/ft_listlen.c.s
.PHONY : sources/list_operations/ft_listlen.s

# target to generate assembly for a file
sources/list_operations/ft_listlen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/ft_listlen.c.s
.PHONY : sources/list_operations/ft_listlen.c.s

sources/list_operations/print_list.o: sources/list_operations/print_list.c.o
.PHONY : sources/list_operations/print_list.o

# target to build an object file
sources/list_operations/print_list.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/print_list.c.o
.PHONY : sources/list_operations/print_list.c.o

sources/list_operations/print_list.i: sources/list_operations/print_list.c.i
.PHONY : sources/list_operations/print_list.i

# target to preprocess a source file
sources/list_operations/print_list.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/print_list.c.i
.PHONY : sources/list_operations/print_list.c.i

sources/list_operations/print_list.s: sources/list_operations/print_list.c.s
.PHONY : sources/list_operations/print_list.s

# target to generate assembly for a file
sources/list_operations/print_list.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/print_list.c.s
.PHONY : sources/list_operations/print_list.c.s

sources/list_operations/remove_element.o: sources/list_operations/remove_element.c.o
.PHONY : sources/list_operations/remove_element.o

# target to build an object file
sources/list_operations/remove_element.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/remove_element.c.o
.PHONY : sources/list_operations/remove_element.c.o

sources/list_operations/remove_element.i: sources/list_operations/remove_element.c.i
.PHONY : sources/list_operations/remove_element.i

# target to preprocess a source file
sources/list_operations/remove_element.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/remove_element.c.i
.PHONY : sources/list_operations/remove_element.c.i

sources/list_operations/remove_element.s: sources/list_operations/remove_element.c.s
.PHONY : sources/list_operations/remove_element.s

# target to generate assembly for a file
sources/list_operations/remove_element.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/list_operations/remove_element.c.s
.PHONY : sources/list_operations/remove_element.c.s

sources/push_swap.o: sources/push_swap.c.o
.PHONY : sources/push_swap.o

# target to build an object file
sources/push_swap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/push_swap.c.o
.PHONY : sources/push_swap.c.o

sources/push_swap.i: sources/push_swap.c.i
.PHONY : sources/push_swap.i

# target to preprocess a source file
sources/push_swap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/push_swap.c.i
.PHONY : sources/push_swap.c.i

sources/push_swap.s: sources/push_swap.c.s
.PHONY : sources/push_swap.s

# target to generate assembly for a file
sources/push_swap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/push_swap.c.s
.PHONY : sources/push_swap.c.s

sources/push_swap_operations/push.o: sources/push_swap_operations/push.c.o
.PHONY : sources/push_swap_operations/push.o

# target to build an object file
sources/push_swap_operations/push.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/push_swap_operations/push.c.o
.PHONY : sources/push_swap_operations/push.c.o

sources/push_swap_operations/push.i: sources/push_swap_operations/push.c.i
.PHONY : sources/push_swap_operations/push.i

# target to preprocess a source file
sources/push_swap_operations/push.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/push_swap_operations/push.c.i
.PHONY : sources/push_swap_operations/push.c.i

sources/push_swap_operations/push.s: sources/push_swap_operations/push.c.s
.PHONY : sources/push_swap_operations/push.s

# target to generate assembly for a file
sources/push_swap_operations/push.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/push_swap_operations/push.c.s
.PHONY : sources/push_swap_operations/push.c.s

sources/push_swap_operations/reverse_rotate.o: sources/push_swap_operations/reverse_rotate.c.o
.PHONY : sources/push_swap_operations/reverse_rotate.o

# target to build an object file
sources/push_swap_operations/reverse_rotate.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/push_swap_operations/reverse_rotate.c.o
.PHONY : sources/push_swap_operations/reverse_rotate.c.o

sources/push_swap_operations/reverse_rotate.i: sources/push_swap_operations/reverse_rotate.c.i
.PHONY : sources/push_swap_operations/reverse_rotate.i

# target to preprocess a source file
sources/push_swap_operations/reverse_rotate.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/push_swap_operations/reverse_rotate.c.i
.PHONY : sources/push_swap_operations/reverse_rotate.c.i

sources/push_swap_operations/reverse_rotate.s: sources/push_swap_operations/reverse_rotate.c.s
.PHONY : sources/push_swap_operations/reverse_rotate.s

# target to generate assembly for a file
sources/push_swap_operations/reverse_rotate.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/push_swap_operations/reverse_rotate.c.s
.PHONY : sources/push_swap_operations/reverse_rotate.c.s

sources/push_swap_operations/rotate.o: sources/push_swap_operations/rotate.c.o
.PHONY : sources/push_swap_operations/rotate.o

# target to build an object file
sources/push_swap_operations/rotate.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/push_swap_operations/rotate.c.o
.PHONY : sources/push_swap_operations/rotate.c.o

sources/push_swap_operations/rotate.i: sources/push_swap_operations/rotate.c.i
.PHONY : sources/push_swap_operations/rotate.i

# target to preprocess a source file
sources/push_swap_operations/rotate.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/push_swap_operations/rotate.c.i
.PHONY : sources/push_swap_operations/rotate.c.i

sources/push_swap_operations/rotate.s: sources/push_swap_operations/rotate.c.s
.PHONY : sources/push_swap_operations/rotate.s

# target to generate assembly for a file
sources/push_swap_operations/rotate.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/push_swap_operations/rotate.c.s
.PHONY : sources/push_swap_operations/rotate.c.s

sources/push_swap_operations/swap.o: sources/push_swap_operations/swap.c.o
.PHONY : sources/push_swap_operations/swap.o

# target to build an object file
sources/push_swap_operations/swap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/push_swap_operations/swap.c.o
.PHONY : sources/push_swap_operations/swap.c.o

sources/push_swap_operations/swap.i: sources/push_swap_operations/swap.c.i
.PHONY : sources/push_swap_operations/swap.i

# target to preprocess a source file
sources/push_swap_operations/swap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/push_swap_operations/swap.c.i
.PHONY : sources/push_swap_operations/swap.c.i

sources/push_swap_operations/swap.s: sources/push_swap_operations/swap.c.s
.PHONY : sources/push_swap_operations/swap.s

# target to generate assembly for a file
sources/push_swap_operations/swap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/push_swap_operations/swap.c.s
.PHONY : sources/push_swap_operations/swap.c.s

sources/sort_algorithm.o: sources/sort_algorithm.c.o
.PHONY : sources/sort_algorithm.o

# target to build an object file
sources/sort_algorithm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_algorithm.c.o
.PHONY : sources/sort_algorithm.c.o

sources/sort_algorithm.i: sources/sort_algorithm.c.i
.PHONY : sources/sort_algorithm.i

# target to preprocess a source file
sources/sort_algorithm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_algorithm.c.i
.PHONY : sources/sort_algorithm.c.i

sources/sort_algorithm.s: sources/sort_algorithm.c.s
.PHONY : sources/sort_algorithm.s

# target to generate assembly for a file
sources/sort_algorithm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_algorithm.c.s
.PHONY : sources/sort_algorithm.c.s

sources/sort_supply/big_element_sort.o: sources/sort_supply/big_element_sort.c.o
.PHONY : sources/sort_supply/big_element_sort.o

# target to build an object file
sources/sort_supply/big_element_sort.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_supply/big_element_sort.c.o
.PHONY : sources/sort_supply/big_element_sort.c.o

sources/sort_supply/big_element_sort.i: sources/sort_supply/big_element_sort.c.i
.PHONY : sources/sort_supply/big_element_sort.i

# target to preprocess a source file
sources/sort_supply/big_element_sort.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_supply/big_element_sort.c.i
.PHONY : sources/sort_supply/big_element_sort.c.i

sources/sort_supply/big_element_sort.s: sources/sort_supply/big_element_sort.c.s
.PHONY : sources/sort_supply/big_element_sort.s

# target to generate assembly for a file
sources/sort_supply/big_element_sort.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_supply/big_element_sort.c.s
.PHONY : sources/sort_supply/big_element_sort.c.s

sources/sort_supply/bubble_sort.o: sources/sort_supply/bubble_sort.c.o
.PHONY : sources/sort_supply/bubble_sort.o

# target to build an object file
sources/sort_supply/bubble_sort.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_supply/bubble_sort.c.o
.PHONY : sources/sort_supply/bubble_sort.c.o

sources/sort_supply/bubble_sort.i: sources/sort_supply/bubble_sort.c.i
.PHONY : sources/sort_supply/bubble_sort.i

# target to preprocess a source file
sources/sort_supply/bubble_sort.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_supply/bubble_sort.c.i
.PHONY : sources/sort_supply/bubble_sort.c.i

sources/sort_supply/bubble_sort.s: sources/sort_supply/bubble_sort.c.s
.PHONY : sources/sort_supply/bubble_sort.s

# target to generate assembly for a file
sources/sort_supply/bubble_sort.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_supply/bubble_sort.c.s
.PHONY : sources/sort_supply/bubble_sort.c.s

sources/sort_supply/small_element_sort.o: sources/sort_supply/small_element_sort.c.o
.PHONY : sources/sort_supply/small_element_sort.o

# target to build an object file
sources/sort_supply/small_element_sort.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_supply/small_element_sort.c.o
.PHONY : sources/sort_supply/small_element_sort.c.o

sources/sort_supply/small_element_sort.i: sources/sort_supply/small_element_sort.c.i
.PHONY : sources/sort_supply/small_element_sort.i

# target to preprocess a source file
sources/sort_supply/small_element_sort.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_supply/small_element_sort.c.i
.PHONY : sources/sort_supply/small_element_sort.c.i

sources/sort_supply/small_element_sort.s: sources/sort_supply/small_element_sort.c.s
.PHONY : sources/sort_supply/small_element_sort.s

# target to generate assembly for a file
sources/sort_supply/small_element_sort.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_supply/small_element_sort.c.s
.PHONY : sources/sort_supply/small_element_sort.c.s

sources/sort_supply/three_element_sort.o: sources/sort_supply/three_element_sort.c.o
.PHONY : sources/sort_supply/three_element_sort.o

# target to build an object file
sources/sort_supply/three_element_sort.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_supply/three_element_sort.c.o
.PHONY : sources/sort_supply/three_element_sort.c.o

sources/sort_supply/three_element_sort.i: sources/sort_supply/three_element_sort.c.i
.PHONY : sources/sort_supply/three_element_sort.i

# target to preprocess a source file
sources/sort_supply/three_element_sort.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_supply/three_element_sort.c.i
.PHONY : sources/sort_supply/three_element_sort.c.i

sources/sort_supply/three_element_sort.s: sources/sort_supply/three_element_sort.c.s
.PHONY : sources/sort_supply/three_element_sort.s

# target to generate assembly for a file
sources/sort_supply/three_element_sort.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_supply/three_element_sort.c.s
.PHONY : sources/sort_supply/three_element_sort.c.s

sources/sort_supply/two_element_sort.o: sources/sort_supply/two_element_sort.c.o
.PHONY : sources/sort_supply/two_element_sort.o

# target to build an object file
sources/sort_supply/two_element_sort.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_supply/two_element_sort.c.o
.PHONY : sources/sort_supply/two_element_sort.c.o

sources/sort_supply/two_element_sort.i: sources/sort_supply/two_element_sort.c.i
.PHONY : sources/sort_supply/two_element_sort.i

# target to preprocess a source file
sources/sort_supply/two_element_sort.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_supply/two_element_sort.c.i
.PHONY : sources/sort_supply/two_element_sort.c.i

sources/sort_supply/two_element_sort.s: sources/sort_supply/two_element_sort.c.s
.PHONY : sources/sort_supply/two_element_sort.s

# target to generate assembly for a file
sources/sort_supply/two_element_sort.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/push_swap.dir/build.make CMakeFiles/push_swap.dir/sources/sort_supply/two_element_sort.c.s
.PHONY : sources/sort_supply/two_element_sort.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... push_swap"
	@echo "... libft/ft_atoi.o"
	@echo "... libft/ft_atoi.i"
	@echo "... libft/ft_atoi.s"
	@echo "... libft/ft_bzero.o"
	@echo "... libft/ft_bzero.i"
	@echo "... libft/ft_bzero.s"
	@echo "... libft/ft_calloc.o"
	@echo "... libft/ft_calloc.i"
	@echo "... libft/ft_calloc.s"
	@echo "... libft/ft_isalnum.o"
	@echo "... libft/ft_isalnum.i"
	@echo "... libft/ft_isalnum.s"
	@echo "... libft/ft_isalpha.o"
	@echo "... libft/ft_isalpha.i"
	@echo "... libft/ft_isalpha.s"
	@echo "... libft/ft_isascii.o"
	@echo "... libft/ft_isascii.i"
	@echo "... libft/ft_isascii.s"
	@echo "... libft/ft_isdigit.o"
	@echo "... libft/ft_isdigit.i"
	@echo "... libft/ft_isdigit.s"
	@echo "... libft/ft_isprint.o"
	@echo "... libft/ft_isprint.i"
	@echo "... libft/ft_isprint.s"
	@echo "... libft/ft_itoa.o"
	@echo "... libft/ft_itoa.i"
	@echo "... libft/ft_itoa.s"
	@echo "... libft/ft_memccpy.o"
	@echo "... libft/ft_memccpy.i"
	@echo "... libft/ft_memccpy.s"
	@echo "... libft/ft_memchr.o"
	@echo "... libft/ft_memchr.i"
	@echo "... libft/ft_memchr.s"
	@echo "... libft/ft_memcmp.o"
	@echo "... libft/ft_memcmp.i"
	@echo "... libft/ft_memcmp.s"
	@echo "... libft/ft_memcpy.o"
	@echo "... libft/ft_memcpy.i"
	@echo "... libft/ft_memcpy.s"
	@echo "... libft/ft_memmove.o"
	@echo "... libft/ft_memmove.i"
	@echo "... libft/ft_memmove.s"
	@echo "... libft/ft_memset.o"
	@echo "... libft/ft_memset.i"
	@echo "... libft/ft_memset.s"
	@echo "... libft/ft_putchar_fd.o"
	@echo "... libft/ft_putchar_fd.i"
	@echo "... libft/ft_putchar_fd.s"
	@echo "... libft/ft_putendl_fd.o"
	@echo "... libft/ft_putendl_fd.i"
	@echo "... libft/ft_putendl_fd.s"
	@echo "... libft/ft_putnbr_fd.o"
	@echo "... libft/ft_putnbr_fd.i"
	@echo "... libft/ft_putnbr_fd.s"
	@echo "... libft/ft_putstr_fd.o"
	@echo "... libft/ft_putstr_fd.i"
	@echo "... libft/ft_putstr_fd.s"
	@echo "... libft/ft_split.o"
	@echo "... libft/ft_split.i"
	@echo "... libft/ft_split.s"
	@echo "... libft/ft_strchr.o"
	@echo "... libft/ft_strchr.i"
	@echo "... libft/ft_strchr.s"
	@echo "... libft/ft_strdup.o"
	@echo "... libft/ft_strdup.i"
	@echo "... libft/ft_strdup.s"
	@echo "... libft/ft_strjoin.o"
	@echo "... libft/ft_strjoin.i"
	@echo "... libft/ft_strjoin.s"
	@echo "... libft/ft_strlcat.o"
	@echo "... libft/ft_strlcat.i"
	@echo "... libft/ft_strlcat.s"
	@echo "... libft/ft_strlcpy.o"
	@echo "... libft/ft_strlcpy.i"
	@echo "... libft/ft_strlcpy.s"
	@echo "... libft/ft_strlen.o"
	@echo "... libft/ft_strlen.i"
	@echo "... libft/ft_strlen.s"
	@echo "... libft/ft_strmapi.o"
	@echo "... libft/ft_strmapi.i"
	@echo "... libft/ft_strmapi.s"
	@echo "... libft/ft_strncmp.o"
	@echo "... libft/ft_strncmp.i"
	@echo "... libft/ft_strncmp.s"
	@echo "... libft/ft_strnstr.o"
	@echo "... libft/ft_strnstr.i"
	@echo "... libft/ft_strnstr.s"
	@echo "... libft/ft_strrchr.o"
	@echo "... libft/ft_strrchr.i"
	@echo "... libft/ft_strrchr.s"
	@echo "... libft/ft_strtrim.o"
	@echo "... libft/ft_strtrim.i"
	@echo "... libft/ft_strtrim.s"
	@echo "... libft/ft_substr.o"
	@echo "... libft/ft_substr.i"
	@echo "... libft/ft_substr.s"
	@echo "... libft/ft_tolower.o"
	@echo "... libft/ft_tolower.i"
	@echo "... libft/ft_tolower.s"
	@echo "... libft/ft_toupper.o"
	@echo "... libft/ft_toupper.i"
	@echo "... libft/ft_toupper.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sources/errors.o"
	@echo "... sources/errors.i"
	@echo "... sources/errors.s"
	@echo "... sources/fill_array.o"
	@echo "... sources/fill_array.i"
	@echo "... sources/fill_array.s"
	@echo "... sources/list_operations/add_element.o"
	@echo "... sources/list_operations/add_element.i"
	@echo "... sources/list_operations/add_element.s"
	@echo "... sources/list_operations/create_list.o"
	@echo "... sources/list_operations/create_list.i"
	@echo "... sources/list_operations/create_list.s"
	@echo "... sources/list_operations/element_position_in_list.o"
	@echo "... sources/list_operations/element_position_in_list.i"
	@echo "... sources/list_operations/element_position_in_list.s"
	@echo "... sources/list_operations/element_to_top.o"
	@echo "... sources/list_operations/element_to_top.i"
	@echo "... sources/list_operations/element_to_top.s"
	@echo "... sources/list_operations/ft_listlen.o"
	@echo "... sources/list_operations/ft_listlen.i"
	@echo "... sources/list_operations/ft_listlen.s"
	@echo "... sources/list_operations/print_list.o"
	@echo "... sources/list_operations/print_list.i"
	@echo "... sources/list_operations/print_list.s"
	@echo "... sources/list_operations/remove_element.o"
	@echo "... sources/list_operations/remove_element.i"
	@echo "... sources/list_operations/remove_element.s"
	@echo "... sources/push_swap.o"
	@echo "... sources/push_swap.i"
	@echo "... sources/push_swap.s"
	@echo "... sources/push_swap_operations/push.o"
	@echo "... sources/push_swap_operations/push.i"
	@echo "... sources/push_swap_operations/push.s"
	@echo "... sources/push_swap_operations/reverse_rotate.o"
	@echo "... sources/push_swap_operations/reverse_rotate.i"
	@echo "... sources/push_swap_operations/reverse_rotate.s"
	@echo "... sources/push_swap_operations/rotate.o"
	@echo "... sources/push_swap_operations/rotate.i"
	@echo "... sources/push_swap_operations/rotate.s"
	@echo "... sources/push_swap_operations/swap.o"
	@echo "... sources/push_swap_operations/swap.i"
	@echo "... sources/push_swap_operations/swap.s"
	@echo "... sources/sort_algorithm.o"
	@echo "... sources/sort_algorithm.i"
	@echo "... sources/sort_algorithm.s"
	@echo "... sources/sort_supply/big_element_sort.o"
	@echo "... sources/sort_supply/big_element_sort.i"
	@echo "... sources/sort_supply/big_element_sort.s"
	@echo "... sources/sort_supply/bubble_sort.o"
	@echo "... sources/sort_supply/bubble_sort.i"
	@echo "... sources/sort_supply/bubble_sort.s"
	@echo "... sources/sort_supply/small_element_sort.o"
	@echo "... sources/sort_supply/small_element_sort.i"
	@echo "... sources/sort_supply/small_element_sort.s"
	@echo "... sources/sort_supply/three_element_sort.o"
	@echo "... sources/sort_supply/three_element_sort.i"
	@echo "... sources/sort_supply/three_element_sort.s"
	@echo "... sources/sort_supply/two_element_sort.o"
	@echo "... sources/sort_supply/two_element_sort.i"
	@echo "... sources/sort_supply/two_element_sort.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

